# Generated by Django 4.1.5 on 2023-01-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_phoneid_profile_phonenumber"),
        ("pages", "0006_remove_navlinkitem_image_testimonial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coins_name",
                    models.CharField(
                        choices=[("BTC", "BTC"), ("ETH", "ETH"), ("DODGE", "DODGE")],
                        max_length=50,
                    ),
                ),
                (
                    "bulk_quantity",
                    models.CharField(help_text="$0 - $50", max_length=50),
                ),
                ("exchange_rate", models.CharField(help_text="750NGN", max_length=250)),
                ("as_at", models.DateTimeField()),
                ("updated_as_at", models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="sectionbanner",
            options={"verbose_name": "About us", "verbose_name_plural": "About us"},
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_rite_wallet", models.CharField(max_length=250)),
                ("client_wallet", models.CharField(max_length=250)),
                ("bank_account_number", models.CharField(max_length=250)),
                ("bank_account_name", models.CharField(max_length=250)),
                (
                    "our_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.ourrate"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
