# Generated by Django 4.1.5 on 2023-01-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_chatsession_trading_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="init",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
