# Generated by Django 4.1.5 on 2023-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_chatsession_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="client_wallet",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="trade_rite_wallet",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="trading_type",
            field=models.CharField(
                blank=True,
                choices=[("BTC", "BTC"), ("ETH", "ETH"), ("DODGE", "DODGE")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ourrate",
            name="updated_as_at",
            field=models.DateField(auto_now=True),
        ),
    ]
