# Generated by Django 4.1.5 on 2023-01-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_alter_chatsession_bank_account_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetStarted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("steps", models.TextField(verbose_name="Get Started Steps")),
            ],
        ),
    ]
