# Generated by Django 4.1.5 on 2023-01-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phoneID",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
